/* Generated by SLOP transpiler */
#include "slop_runtime.h"
#include <stdint.h>
#include <stdbool.h>

/* Module: fizzbuzz */

typedef enum {
    FizzBuzzResult_Fizz,
    FizzBuzzResult_Buzz,
    FizzBuzzResult_FizzBuzz,
    FizzBuzzResult_Number
} FizzBuzzResult;

/* Forward declarations */
FizzBuzzResult fizzbuzz(int64_t n);
int main(void);

/* Return Fizz for multiples of 3, Buzz for multiples of 5, FizzBuzz for both, Number otherwise */
FizzBuzzResult fizzbuzz(int64_t n) {
    if (((n % 15) == 0)) {
        return FizzBuzzResult_FizzBuzz;
    } else if (((n % 3) == 0)) {
        return FizzBuzzResult_Fizz;
    } else if (((n % 5) == 0)) {
        return FizzBuzzResult_Buzz;
    } else {
        return FizzBuzzResult_Number;
    }
}

/* Print fizzbuzz for numbers 1 to 100 */
int main(void) {
    {
        slop_arena _arena = slop_arena_new(1024);
        slop_arena* arena = &_arena;
        for (int64_t i = 1; i < 101; i++) {
            __auto_type result = fizzbuzz(i);
            switch (result) {
                case FizzBuzzResult_Fizz: {
                    printf("%s\n", (SLOP_STR("Fizz")).data);
                    break;
                }
                case FizzBuzzResult_Buzz: {
                    printf("%s\n", (SLOP_STR("Buzz")).data);
                    break;
                }
                case FizzBuzzResult_FizzBuzz: {
                    printf("%s\n", (SLOP_STR("FizzBuzz")).data);
                    break;
                }
                case FizzBuzzResult_Number: {
                    printf("%s\n", (int_to_string(arena, i)).data);
                    break;
                }
            }
        }
        return 0;
        slop_arena_free(arena);
    }
}
