"""Tests for `slop derive` from JSON Schema and SQL DDL.

The unit tests pin the mapping; the native tests run the derived module
through `slop check` and `slop build`, since output the compiler rejects is
the failure that matters.
"""

import pytest

from slop.schema_converter import JsonSchemaConverter, SqlSchemaConverter

from derive_helpers import (
    FIXTURES, add_main, assert_checks, build_and_run, derive, requires_native, slop,
)


def json_convert(schema, name="Root"):
    converter = JsonSchemaConverter()
    return converter.convert(schema, name), converter


def sql_convert(sql):
    converter = SqlSchemaConverter()
    return converter.convert(sql), converter


class TestJsonSchemaTypes:

    def test_output_is_a_module_exporting_its_types(self):
        out, _ = json_convert({"type": "object", "properties": {"id": {"type": "integer"}}},
                              "User")
        assert out.startswith(";; Generated by slop derive from JSON Schema\n(module user\n")
        assert "(export User)" in out
        assert out.rstrip().endswith(")")

    def test_string_enum_keeps_its_values(self):
        # `type` used to be dispatched before `enum`, so this became String.
        out, _ = json_convert({"type": "object", "properties": {
            "status": {"type": "string", "enum": ["active", "inactive"]}},
            "required": ["status"]}, "User")
        assert "(type UserStatus (enum active inactive))" in out
        assert "(status UserStatus)" in out

    def test_enum_values_become_identifiers(self):
        out, conv = json_convert({"enum": ["1.0", "2.0-beta", "", "Release Candidate",
                                           "UPPER_CASE", "camelCase", "none", "Active",
                                           "active"]}, "Version")
        assert ("(enum v-1-0 v-2-0-beta empty release-candidate upper-case camel-case "
                "version-none active active-2)") in out
        # The JSON spelling is kept in a comment, since the variants differ.
        assert ';; JSON values: "1.0" "2.0-beta" ""' in out
        assert conv.enum_values["Version"]["Release Candidate"] == "release-candidate"

    def test_variants_unique_across_enums(self):
        out, _ = json_convert({"type": "object", "properties": {
            "a": {"enum": ["red", "draft"]},
            "b": {"enum": ["blue", "draft"]}}}, "Doc")
        assert "(type DocA (enum red draft))" in out
        assert "(type DocB (enum blue doc-b-draft))" in out

    def test_identical_inline_enums_share_one_type(self):
        out, _ = json_convert({"type": "object", "properties": {
            "a": {"enum": ["x", "y"]}, "b": {"enum": ["x", "y"]}}}, "Doc")
        assert out.count("(enum x y)") == 1
        assert "(b (Option DocA))" in out

    def test_union_tags_are_unique_across_unions(self):
        # Every union used to tag its variants v0, v1, ... so two unions in one
        # module made 'v0' ambiguous.
        out, _ = json_convert({
            "type": "object",
            "properties": {
                "first": {"oneOf": [{"$ref": "#/$defs/Circle"}, {"$ref": "#/$defs/Square"}]},
                "second": {"oneOf": [{"$ref": "#/$defs/Circle"}, {"type": "string"}]},
            },
            "$defs": {
                "Circle": {"type": "object", "properties": {"r": {"type": "number"}}},
                "Square": {"type": "object", "properties": {"s": {"type": "number"}}},
            }}, "Shape")
        assert "(circle Circle)" in out
        assert "(square Square)" in out
        assert "(shape-second-circle Circle)" in out
        assert "(shape-second-1 String)" in out
        assert "(v0 " not in out

    def test_null_alternative_makes_an_option(self):
        out, _ = json_convert({"type": "object", "properties": {
            "label": {"anyOf": [{"type": "string"}, {"type": "null"}]},
            "tags": {"type": ["array", "null"], "items": {"type": "string"}},
            "ratio": {"type": "number", "nullable": True}},
            "required": ["label", "tags", "ratio"]}, "Doc")
        assert "(label (Option String))" in out
        assert "(tags (Option (List String)))" in out
        assert "(ratio (Option Float))" in out
        assert "(Option (Option" not in out

    def test_dates_are_strings_with_their_format(self):
        out, _ = json_convert({"type": "object", "properties": {
            "at": {"type": "string", "format": "date-time"},
            "on": {"type": "string", "format": "date"}},
            "required": ["at", "on"]}, "Doc")
        assert ";; format: date-time\n      (at String)" in out
        assert ";; format: date\n      (on String)" in out
        assert "DateTime" not in out and "(on Date)" not in out

    def test_string_const_is_a_single_variant_enum(self):
        out, _ = json_convert({"type": "object", "properties": {
            "kind": {"const": "circle"}, "n": {"const": 3}},
            "required": ["kind", "n"]}, "Shape")
        assert "(type ShapeKind (enum circle))" in out
        assert ";; const: 3\n      (n Int)" in out

    def test_all_of_merges_object_parts(self):
        out, _ = json_convert({"$defs": {
            "Named": {"type": "object", "properties": {"name": {"type": "string"}},
                      "required": ["name"]},
            "Person": {"allOf": [{"$ref": "#/$defs/Named"},
                                 {"properties": {"age": {"type": "integer"}}}]}}})
        assert "(type Person (record\n      (name String)\n      (age (Option Int))))" in out

    def test_named_primitive_schema_is_an_alias(self):
        # A $ref to it must resolve to a defined type.
        out, _ = json_convert({"type": "object", "properties": {"age": {"$ref": "#/$defs/Age"}},
                               "$defs": {"Age": {"type": "integer", "minimum": 0}}}, "P")
        assert "(type Age (Int 0 ..))" in out
        assert "(age (Option Age))" in out

    def test_self_reference_goes_through_a_pointer(self):
        out, _ = json_convert({"$defs": {"Node": {"type": "object", "properties": {
            "next": {"$ref": "#/$defs/Node"}}}}})
        assert "(next (Option (Ptr Node)))" in out

    def test_reserved_type_names_are_renamed(self):
        out, _ = json_convert({"$defs": {"String": {"type": "object", "properties": {
            "v": {"type": "string"}}}}})
        assert "(type StringSchema (record" in out

    def test_unsupported_schema_is_string_with_warning(self):
        out, conv = json_convert({"type": "object", "properties": {
            "meta": {"type": "object"}, "any": {}, "mixed": {"enum": ["a", 1]}}}, "Doc")
        assert "Any" not in out
        assert ";; free-form object: kept as String (JSON text)\n      (meta (Option String))" in out
        assert "(any (Option String))" in out
        assert "(mixed (Option String))" in out
        assert len(conv.warnings) == 3
        assert conv.warnings[0] == "DocMeta: free-form object; using String"

    def test_additional_properties_is_a_map(self):
        out, _ = json_convert({"type": "object", "properties": {
            "counts": {"type": "object", "additionalProperties": {"type": "integer"}}},
            "required": ["counts"]}, "Doc")
        assert "(counts (Map String Int))" in out

    def test_odd_property_names_become_fields(self):
        out, _ = json_convert({"type": "object", "properties": {
            "@type": {"type": "string"}, "fooBar": {"type": "string"},
            "foo_bar": {"type": "string"}, "2fa": {"type": "boolean"}}}, "Doc")
        assert ';; JSON property "@type"\n      (type (Option String))' in out
        assert "(foo-bar (Option String))" in out
        assert "(foo-bar-2 (Option String))" in out
        assert "(field-2fa (Option Bool))" in out


class TestSqlTypes:

    def test_create_table_forms(self):
        out, _ = sql_convert('''
            CREATE TABLE IF NOT EXISTS users (id INT NOT NULL);
            CREATE TABLE "public"."order items" ("order id" INT NOT NULL);
            CREATE TABLE `products` (`sku` INT NOT NULL);
            CREATE TABLE [dbo].[line] ([n] INT NOT NULL);
        ''')
        assert "(type Users (record" in out
        assert "(type OrderItems (record\n      (order-id Int)))" in out
        assert "(type Products (record\n      (sku Int)))" in out
        assert "(type Line (record\n      (n Int)))" in out
        assert ";; From table: public.order items" in out

    def test_inline_constraints_keep_the_column(self):
        # Any column whose definition mentioned PRIMARY KEY, UNIQUE, CHECK or
        # INDEX used to be dropped, along with checksum and index_id.
        out, _ = sql_convert('''CREATE TABLE t (
            id INTEGER PRIMARY KEY,
            email VARCHAR(255) UNIQUE NOT NULL,
            age INT CHECK (age >= 0),
            checksum CHAR(64) NOT NULL,
            index_id BIGINT,
            key VARCHAR(10)
        );''')
        # A primary key is never optional.
        assert "(id Int)" in out
        assert "(email (String .. 255))" in out
        assert "(age (Option Int))" in out
        assert "(checksum (String .. 64))" in out
        assert "(index-id (Option I64))" in out
        assert "(key (Option (String .. 10)))" in out

    def test_table_constraints_are_skipped_and_pk_columns_required(self):
        out, _ = sql_convert('''CREATE TABLE pairs (
            a INT, b INT, c INT,
            CONSTRAINT pk PRIMARY KEY (a, b),
            FOREIGN KEY (c) REFERENCES u (id),
            UNIQUE (c),
            CHECK (c > 0),
            KEY idx_c (c),
            INDEX idx_b (b)
        );''')
        assert "(type Pairs (record\n      (a Int)\n      (b Int)\n      (c (Option Int))))" in out

    def test_parameterized_types(self):
        out, _ = sql_convert('''CREATE TABLE t (
            price DECIMAL(10, 2) NOT NULL,
            n INT(11) NOT NULL,
            w FLOAT(53) NOT NULL,
            f FLOAT NOT NULL,
            id SERIAL,
            big BIGSERIAL,
            u SMALLINT UNSIGNED NOT NULL,
            name CHARACTER VARYING(40) NOT NULL,
            tags TEXT[] NOT NULL,
            at TIMESTAMP WITH TIME ZONE NOT NULL
        );''')
        assert ";; DECIMAL(10, 2): exact decimal held as Float\n      (price Float)" in out
        assert "(n Int)" in out
        assert "(w Float)" in out
        assert "(f F32)" in out
        # SERIAL is NOT NULL by construction.
        assert "(id Int)" in out
        assert "(big I64)" in out
        assert "(u U16)" in out
        assert "(name (String .. 40))" in out
        assert "(tags (List String))" in out
        assert ";; TIMESTAMP: kept as String\n      (at String)" in out
        assert "Any" not in out and "DateTime" not in out

    def test_length_comes_from_the_type_only(self):
        # The length regex used to scan the whole definition, so the CHECK's
        # (5) gave TEXT a length.
        out, _ = sql_convert("CREATE TABLE t (b BLOB CHECK (length(b) < 5));")
        assert "(b (Option Bytes))" in out

    def test_postgres_enum_type(self):
        out, _ = sql_convert('''
            CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');
            CREATE TABLE t (m mood NOT NULL);''')
        # `ok` is a builtin variant, so that one is prefixed.
        assert "(type Mood (enum sad mood-ok happy))" in out
        assert "(m Mood)" in out

    def test_unknown_type_is_string_with_warning(self):
        out, conv = sql_convert("CREATE TABLE t (g GEOMETRY);")
        assert ";; unsupported SQL type GEOMETRY: kept as String\n      (g (Option String))" in out
        assert conv.warnings == ["t.g: unsupported SQL type GEOMETRY; using String"]

    def test_comments_are_ignored(self):
        out, _ = sql_convert('''CREATE TABLE notes (
            a INT NOT NULL, -- a comment, with a comma
            /* b INT, */ c INT NOT NULL
        );''')
        assert "(type Notes (record\n      (a Int)\n      (c Int)))" in out
        # A single-letter type name would read as a type variable.
        assert "(type TType (record" in sql_convert("CREATE TABLE t (a INT);")[0]


@requires_native
class TestDerivedModulesBuild:
    """The derived module must pass slop check and build as it stands."""

    def test_json_schema_fixture(self, tmp_path):
        path, stderr = derive(tmp_path, "drawing.json", "drawing")
        assert "warning: DrawingMetadata: free-form object; using String" in stderr
        assert_checks(path)
        # Construct a value of a derived union through its derived tag.
        body = ("(let ((p (union-new DrawingPrimary circle "
                "(record-new Circle (radius 1.0) (fill (none))))))\n"
                "      (match p ((circle c) 0) ((square s) 1)))")
        path.write_text(add_main(path.read_text(), body))
        assert build_and_run(path, tmp_path) == 0

    def test_sql_fixture(self, tmp_path):
        path, stderr = derive(tmp_path, "shop.sql", "shop")
        assert "unsupported SQL type GEOMETRY" in stderr
        text = path.read_text()
        assert "(module shop" in text
        assert_checks(path)
        body = ("(let ((u (record-new Products (sku \"A1\") (id 1) (price (some 2.5)))))\n"
                "      (- (. u id) 1))")
        path.write_text(add_main(text, body))
        assert build_and_run(path, tmp_path) == 0

    def test_module_name_follows_the_output_file(self, tmp_path):
        out = tmp_path / "my_types.slop"
        slop("derive", FIXTURES / "shop.sql", "-o", out, check=True)
        assert "(module my_types" in out.read_text()

    def test_stdout_module_name_follows_the_input(self):
        result = slop("derive", FIXTURES / "drawing.json", check=True)
        assert "(module drawing" in result.stdout
